### ISSUE TITLE
文案会被折叠 - 对比godbiao和小程序

### ISSUE THREAD

**Issue by yymmm9** [woytu/no-folding#2]
同样的文案用以下工具测试了下
no-folding.pages.dev
godbiao.com/tools/bzd
防折叠小程序 

第一个会被折叠，剩下的都不会被折叠

**Comment by bajins** [comment]
> 同样的文案用以下工具测试了下 no-folding.pages.dev godbiao.com/tools/bzd 防折叠小程序
> 
> 第一个会被折叠，剩下的都不会被折叠

感谢反馈，已经修复，请帮忙再次测试一下
